# Generated by Django 5.0.4 on 2024-04-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=40)),
                ('contactname', models.CharField(blank=True, max_length=30, null=True)),
                ('contacttitle', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(blank=True, max_length=15, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('fax', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
    ]
